name: Tenant Validator
on:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev, stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]   
   
jobs:
  api-validator: 
    uses: ./.github/workflows/github-yaml-validator.yaml
    if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) && (github.event.path == 'reference/**')}}
  # docs-validator: 
  #   uses: Fiserv/remote-actions/.github/workflows/github-md-validator.yaml@develop
  #   if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) && (github.event.path == 'docs/**')}}  
  tenant-config-validator: 
    uses: ./.github/workflows/github-tenant-config-validator.yaml
    if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) && (github.event.path == 'config/tenant.json')}}
  api-zip-generator:
    needs: api-validator
    uses: ./.github/workflows/github-zip-generator.yaml
    if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) && (github.event.path == 'reference/**')}}
